
# **Jiyue Qin**

> jq2293@columbia.edu | 100 Haven Avenue, NY, 10032

## **Education**

**Columbia Univiersiy**

1st graduate student in Biostatistics

_09. 2018 - current_ 

**Huazhong University of Science and Technology (HUST)**

B.S. in Bioscience

_09. 2014 - 06. 2018_ 

GPA: 3.85  
  
**University of California, Berkeley**

concurrent enrollment progam 

_01. 2017- 05. 2017_                                                      

Core courses: Developmental Biology, Cell and Systems Biology, and Neurobiology of Disease

GPA: 4.0


## **Experience**

**Ning's lab, HUST, China**

Research assistant

_08. 2017 - 06. 2018_

Project: Gut microbiome of an unindustrialized population have characteristic enrichment of SNPs in species and functions with the succession of seasons

**Frasergen, Wuhan, China**

Bioinformatics analyst

_03.2018 - 05. 2018_

- developed the pipeline for comparative genomic analysis using Python.

- conducted the comparative genomic analysis for _Spirodela polyrhiza_.

**iGEM 2016 Giant Jamboree, Boston, U.S.**

**Gold Medal**

Member of HUST-China Team 

_10.27.2016 - 10.31.2016_  

Project: [A Signal Filter based on Positive Feedback](http://2016.igem.org/Team:HUST-China) 

## **Skills**

Skilled in Microsoft Word, Excel and PowerPoint

Familiar with R, Python, SPSS.
